/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocsHeading: typeof import('./src/components/DocsHeading.vue')['default']
    HomeCertificatesList: typeof import('./src/components/HomeCertificatesList.vue')['default']
    HomeIntro: typeof import('./src/components/HomeIntro.vue')['default']
    HomeProjectsList: typeof import('./src/components/HomeProjectsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
